name = "relocation-z-2025-worker"
main = "worker/index.ts"
compatibility_date = "2025-08-01"

# Serve the built SPA; SPA routing fallback handled automatically
[assets]
directory = "web/dist"
not_found_handling = "single-page-application"
binding = "ASSETS"

# Cloudflare Pages configuration for wrangler
[pages]
pages_build_output_dir = "web/dist"



